### ISSUE TITLE
Wait for completion of cell before waiting `step_ms` milliseconds?

### ISSUE THREAD

**Issue by fangohr** [minrk/nbautoplay#1]
From the behaviour of using nbautoplay, it appears that it moves to executing the next cell after `step_ms` milliseconds. Would it be possible to start this interval after the previous cell has completed, rather than started?

I am asking as I have a use case where some cells take a fair number of seconds (10 to 30) to complete, and we then run into strange behaviour where the auto-execution highlights cells further down the notebook but the actual execution can't catch up.

**Comment by minrk** [comment]
I think I can make that happen.

**Comment by minrk** [comment]
It will now wait for idle before advancing to the next cell

**Comment by minrk** [comment]
It's not quite the requested behavior, because rather than delaying the timer until idle comes back, the timer event remains on the same interval. But if the step timer fires and the kernel is busy, it will do nothing and wait for the next interval. The effect is that instead of the interval being `exec_time + interval` it's `exec_time + interval % exec_time`

**Comment by fangohr** [comment]
That's great - thank you!
